import {
  createContext,
  type PropsWithChildren,
  useContext,
  useEffect,
  useMemo,
  useState,
} from 'react'

export type Language = 'es' | 'en'

const es = {
  'common.cancel': 'Cancelar',
  'common.close': 'Cerrar',
  'common.optional': 'opcional',
  'common.save': 'Guardar',
  'common.saveChanges': 'Guardar cambios',
  'common.loading': 'Cargando Duet…',
  'common.retry': 'Volver a intentar',
  'nav.home': 'Inicio',
  'nav.wishlist': 'Deseos',
  'nav.notes': 'Notas',
  'nav.links': 'Enlaces',
  'nav.settings': 'Ajustes',
  'nav.mainLabel': 'Navegación principal',
  'nav.mobileLabel': 'Navegación móvil',
  'nav.goHome': 'Ir al inicio de Duet',
  'nav.signOut': 'Cerrar sesión',
  'nav.collapse': 'Ocultar navegación',
  'nav.expand': 'Mostrar navegación',
  'space.label': 'Vuestro espacio',
  'quickAdd.button': 'Añadir algo',
  'quickAdd.label': 'Qué quieres añadir',
  'quickAdd.question': '¿Qué queréis guardar?',
  'quickAdd.wish': 'Un deseo',
  'quickAdd.wishDescription': 'Algo que os haga ilusión',
  'quickAdd.note': 'Una nota',
  'quickAdd.noteDescription': 'Una idea o recordatorio',
  'quickAdd.link': 'Un enlace',
  'quickAdd.linkDescription': 'Un sitio que guardar',
  'modal.eyebrow': 'Añadir a vuestro espacio',
  'modal.editDescription': 'Cambia lo que necesites y vuelve a guardarlo.',
  'item.title': 'Título',
  'item.url': 'Enlace',
  'item.note': 'Nota',
  'item.details': 'Detalles',
  'item.open': 'Abrir',
  'item.you': 'Tú',
  'item.partner': 'Tu pareja',
  'item.pinned': 'Fijado',
  'item.pin': 'Fijar',
  'item.unpin': 'Desfijar',
  'item.edit': 'Editar',
  'item.delete': 'Eliminar',
  'item.options': 'Opciones de {title}',
  'item.deleteConfirm': '¿Eliminar “{title}”?',
  'item.placeholderWishTitle': 'Esa cafetera tan bonita',
  'item.placeholderWishDescription': 'Tamaño, color, para qué ocasión…',
  'item.placeholderNoteTitle': 'Algo que no queremos olvidar',
  'item.placeholderNoteDescription': 'Escribe aquí vuestra nota…',
  'item.placeholderLinkTitle': 'Un sitio para la próxima escapada',
  'item.placeholderLinkDescription': '¿Por qué merece la pena guardarlo?',
  'collection.loadError': 'No se pudo cargar el contenido: {error}',
  'collection.add': 'Añadir {item}',
  'collection.edit': 'Editar {item}',
  'collection.new': 'Nuevo {item}',
  'collection.save': 'Guardar {item}',
  'collection.wishlist.eyebrow': 'Para algún día',
  'collection.wishlist.title': 'Nuestra lista de',
  'collection.wishlist.highlighted': 'deseos',
  'collection.wishlist.description': 'Pequeñas y grandes cosas que os hacen ilusión.',
  'collection.wishlist.singular': 'deseo',
  'collection.wishlist.emptyTitle': 'Aún no hay deseos por aquí',
  'collection.wishlist.emptyDescription': 'Añadid algo que os apetezca comprar, vivir o regalar.',
  'collection.note.eyebrow': 'Entre nosotros',
  'collection.note.title': 'Nuestras',
  'collection.note.highlighted': 'notas',
  'collection.note.description': 'Ideas, recordatorios y palabras que queréis conservar.',
  'collection.note.singular': 'nota',
  'collection.note.emptyTitle': 'Una página por estrenar',
  'collection.note.emptyDescription': 'Escribid algo que queráis recordar los dos.',
  'collection.link.eyebrow': 'Para volver después',
  'collection.link.title': 'Nuestros',
  'collection.link.highlighted': 'enlaces',
  'collection.link.description': 'Restaurantes, viajes, recetas y hallazgos compartidos.',
  'collection.link.singular': 'enlace',
  'collection.link.emptyTitle': 'Guardad vuestro primer hallazgo',
  'collection.link.emptyDescription': 'Ese sitio, receta o idea que no queréis perder.',
  'dashboard.subtitle': 'Aquí tenéis todo lo que estáis construyendo juntos.',
  'dashboard.pinnedEyebrow': 'A mano',
  'dashboard.pinnedTitle': 'Fijado para los dos',
  'dashboard.recentEyebrow': 'Últimos detalles',
  'dashboard.recentTitle': 'Lo más reciente',
  'dashboard.emptyTitle': 'Vuestro espacio empieza aquí',
  'dashboard.emptyDescription': 'Guardad ese primer deseo, una nota bonita o el enlace de vuestro próximo plan.',
  'dashboard.addFirst': 'Añadir lo primero',
  'dashboard.allPinned': 'Todo lo que habéis guardado está fijado arriba.',
  'greeting.morning': 'Buenos días',
  'greeting.afternoon': 'Buenas tardes',
  'greeting.evening': 'Buenas noches',
  'settings.eyebrow': 'Vuestro Duet',
  'settings.title': 'Ajustes',
  'settings.subtitle': 'Personaliza tu perfil, la apariencia y la seguridad.',
  'settings.profileTitle': 'Tu perfil',
  'settings.profileDescription': 'Así aparecerás en el contenido que crees.',
  'settings.changePhoto': 'Cambiar foto',
  'settings.uploading': 'Subiendo…',
  'settings.removePhoto': 'Eliminar foto',
  'settings.photoHelp': 'JPG, PNG o WebP · máximo 2 MB',
  'settings.name': 'Nombre',
  'settings.yourColor': 'Tu color',
  'settings.colorInUse': 'Este color ya lo usa tu pareja',
  'settings.saveProfile': 'Guardar perfil',
  'settings.appearanceTitle': 'Apariencia',
  'settings.appearanceDescription': 'Se guarda únicamente en este dispositivo.',
  'settings.theme': 'Tema',
  'settings.light': 'Claro',
  'settings.dark': 'Oscuro',
  'settings.system': 'Sistema',
  'settings.accent': 'Color de acento',
  'settings.language': 'Idioma',
  'settings.languageDescription': 'El idioma también se guarda en este dispositivo.',
  'settings.spanish': 'Español',
  'settings.english': 'English',
  'settings.spaceTitle': 'Espacio compartido',
  'settings.spaceDescription': 'El nombre que veréis al entrar.',
  'settings.ownerOnly': 'Solo quien creó el espacio puede cambiar este nombre.',
  'settings.inviteTitle': 'Invita a tu pareja',
  'settings.inviteDescription': 'Comparte este código una sola vez.',
  'settings.copyCode': 'Copiar código',
  'settings.inviteHelp': 'Quien use el código podrá ver y editar el contenido compartido.',
  'settings.passwordTitle': 'Cambiar contraseña',
  'settings.passwordDescription': 'No envía emails y se aplica inmediatamente.',
  'settings.newPassword': 'Nueva contraseña',
  'settings.repeatPassword': 'Repite la contraseña',
  'settings.updatePassword': 'Actualizar contraseña',
  'settings.session': 'Sesión',
  'settings.role': 'Rol',
  'settings.owner': 'Creador/a',
  'settings.member': 'Miembro',
  'settings.profileUpdated': 'Perfil actualizado.',
  'settings.spaceUpdated': 'Nombre actualizado.',
  'settings.photoUpdated': 'Foto actualizada.',
  'settings.photoRemoved': 'Foto eliminada.',
  'settings.passwordUpdated': 'Contraseña actualizada correctamente.',
  'settings.passwordMismatch': 'Las contraseñas no coinciden.',
  'settings.invalidPhoto': 'Usa una imagen JPG, PNG o WebP.',
  'settings.photoTooLarge': 'La imagen no puede superar 2 MB.',
  'color.coral': 'Coral',
  'color.sage': 'Salvia',
  'color.blue': 'Océano',
  'color.plum': 'Ciruela',
  'color.amber': 'Ámbar',
  'color.rose': 'Rosa',
  'color.ocean': 'Océano',
  'color.forest': 'Bosque',
  'auth.kicker': 'Solo para vosotros',
  'auth.storyTitle': 'Todo lo vuestro,',
  'auth.storyHighlight': 'en un mismo lugar.',
  'auth.storyDescription': 'Ideas, detalles, planes y pequeñas cosas que merece la pena guardar.',
  'auth.sampleNoteLabel': 'NOTA PARA LOS DOS',
  'auth.sampleNote': 'Reservar nuestro sitio favorito para el viernes ✦',
  'auth.sampleWishLabel': 'PRÓXIMA ESCAPADA',
  'auth.sampleWish': 'Una casa frente al mar',
  'auth.footer': 'Nuestro rincón, a nuestra manera.',
  'auth.welcome': 'Bienvenidos de nuevo',
  'auth.recoverAccess': 'Recuperar acceso',
  'auth.enterTitle': 'Entrad en vuestro espacio',
  'auth.recoverTitle': 'Recupera tu contraseña',
  'auth.enterDescription': 'Un lugar privado para todo lo que compartís.',
  'auth.recoverDescription': 'Te enviaremos un enlace para elegir una contraseña nueva.',
  'auth.email': 'Email',
  'auth.password': 'Contraseña',
  'auth.enter': 'Entrar en Duet',
  'auth.sendLink': 'Enviar enlace',
  'auth.forgotPassword': 'He olvidado mi contraseña',
  'auth.backToLogin': 'Volver al inicio de sesión',
  'auth.recoverySent': 'Revisa tu correo. El enlace puede tardar unos minutos.',
  'auth.privacy': 'Vuestros datos están protegidos y son privados.',
  'reset.ready': 'Todo listo',
  'reset.updatedTitle': 'Contraseña actualizada',
  'reset.updatedDescription': 'Ya puedes seguir usando Duet con tu nueva contraseña.',
  'reset.enter': 'Entrar en Duet',
  'reset.title': 'Elige una contraseña nueva',
  'reset.description': 'Utiliza al menos ocho caracteres y no reutilices otra contraseña.',
  'reset.save': 'Guardar contraseña',
  'onboarding.eyebrow': 'Empecemos',
  'onboarding.title': 'Cread vuestro espacio',
  'onboarding.description': 'Solo tenéis que hacerlo una vez. Después, todo lo que guardéis aparecerá para ambos.',
  'onboarding.createTab': 'Crear espacio',
  'onboarding.joinTab': 'Tengo un código',
  'onboarding.spaceName': 'Nombre de vuestro espacio',
  'onboarding.spaceHelp': 'Podréis cambiarlo en ajustes.',
  'onboarding.code': 'Código de invitación',
  'onboarding.codeHelp': 'Pídeselo a la persona que creó el espacio.',
  'onboarding.create': 'Crear nuestro espacio',
  'onboarding.join': 'Unirme al espacio',
  'setup.eyebrow': 'Un último paso',
  'setup.title': 'Conecta Duet con Supabase',
  'setup.description': 'La aplicación ya está lista. Solo necesita las credenciales públicas de vuestro proyecto para guardar y proteger el contenido.',
  'setup.projectTitle': 'Crea un proyecto',
  'setup.projectDescription': 'En Supabase y ejecuta la migración de la carpeta supabase/migrations.',
  'setup.keysTitle': 'Añade las claves',
  'setup.keysDescription': 'Copia .env.example como .env.local y completa sus dos valores.',
  'setup.startTitle': 'Arranca la app',
  'setup.startDescription': 'Reinicia npm run dev después de guardar el entorno.',
  'setup.open': 'Abrir Supabase',
  'error.noAccess': 'No hemos podido entrar',
  'error.genericTitle': 'Algo no ha ido bien',
  'error.unexpected': 'Ha ocurrido algo inesperado. Inténtalo de nuevo.',
  'error.noCouple': 'No hay una pareja activa.',
  'error.supabase': 'Supabase no está configurado.',
} as const

const en: Record<keyof typeof es, string> = {
  'common.cancel': 'Cancel', 'common.close': 'Close', 'common.optional': 'optional', 'common.save': 'Save', 'common.saveChanges': 'Save changes', 'common.loading': 'Loading Duet…', 'common.retry': 'Try again',
  'nav.home': 'Home', 'nav.wishlist': 'Wishlist', 'nav.notes': 'Notes', 'nav.links': 'Links', 'nav.settings': 'Settings', 'nav.mainLabel': 'Main navigation', 'nav.mobileLabel': 'Mobile navigation', 'nav.goHome': 'Go to Duet home', 'nav.signOut': 'Sign out', 'nav.collapse': 'Collapse navigation', 'nav.expand': 'Expand navigation',
  'space.label': 'Your space',
  'quickAdd.button': 'Add something', 'quickAdd.label': 'Choose what to add', 'quickAdd.question': 'What would you like to save?', 'quickAdd.wish': 'A wish', 'quickAdd.wishDescription': 'Something to look forward to', 'quickAdd.note': 'A note', 'quickAdd.noteDescription': 'An idea or reminder', 'quickAdd.link': 'A link', 'quickAdd.linkDescription': 'A place worth saving',
  'modal.eyebrow': 'Add to your space', 'modal.editDescription': 'Change anything you need and save it again.',
  'item.title': 'Title', 'item.url': 'Link', 'item.note': 'Note', 'item.details': 'Details', 'item.open': 'Open', 'item.you': 'You', 'item.partner': 'Your partner', 'item.pinned': 'Pinned', 'item.pin': 'Pin', 'item.unpin': 'Unpin', 'item.edit': 'Edit', 'item.delete': 'Delete', 'item.options': 'Options for {title}', 'item.deleteConfirm': 'Delete “{title}”?',
  'item.placeholderWishTitle': 'That beautiful coffee maker', 'item.placeholderWishDescription': 'Size, colour, occasion…', 'item.placeholderNoteTitle': 'Something we do not want to forget', 'item.placeholderNoteDescription': 'Write your note here…', 'item.placeholderLinkTitle': 'A place for our next getaway', 'item.placeholderLinkDescription': 'Why is it worth saving?',
  'collection.loadError': 'Could not load the content: {error}', 'collection.add': 'Add {item}', 'collection.edit': 'Edit {item}', 'collection.new': 'New {item}', 'collection.save': 'Save {item}',
  'collection.wishlist.eyebrow': 'For someday', 'collection.wishlist.title': 'Our', 'collection.wishlist.highlighted': 'wishlist', 'collection.wishlist.description': 'Little and big things we are excited about.', 'collection.wishlist.singular': 'wish', 'collection.wishlist.emptyTitle': 'No wishes here yet', 'collection.wishlist.emptyDescription': 'Add something you would like to buy, experience or give.',
  'collection.note.eyebrow': 'Between us', 'collection.note.title': 'Our', 'collection.note.highlighted': 'notes', 'collection.note.description': 'Ideas, reminders and words you want to keep.', 'collection.note.singular': 'note', 'collection.note.emptyTitle': 'A fresh page', 'collection.note.emptyDescription': 'Write something you both want to remember.',
  'collection.link.eyebrow': 'For later', 'collection.link.title': 'Our', 'collection.link.highlighted': 'links', 'collection.link.description': 'Restaurants, trips, recipes and shared discoveries.', 'collection.link.singular': 'link', 'collection.link.emptyTitle': 'Save your first discovery', 'collection.link.emptyDescription': 'That place, recipe or idea you do not want to lose.',
  'dashboard.subtitle': 'Everything you are building together, all in one place.', 'dashboard.pinnedEyebrow': 'Close at hand', 'dashboard.pinnedTitle': 'Pinned for both of you', 'dashboard.recentEyebrow': 'Latest details', 'dashboard.recentTitle': 'Most recent', 'dashboard.emptyTitle': 'Your space starts here', 'dashboard.emptyDescription': 'Save your first wish, a lovely note or the link to your next plan.', 'dashboard.addFirst': 'Add the first thing', 'dashboard.allPinned': 'Everything you have saved is pinned above.',
  'greeting.morning': 'Good morning', 'greeting.afternoon': 'Good afternoon', 'greeting.evening': 'Good evening',
  'settings.eyebrow': 'Your Duet', 'settings.title': 'Settings', 'settings.subtitle': 'Personalise your profile, appearance and security.', 'settings.profileTitle': 'Your profile', 'settings.profileDescription': 'This is how you will appear on the content you create.', 'settings.changePhoto': 'Change photo', 'settings.uploading': 'Uploading…', 'settings.removePhoto': 'Remove photo', 'settings.photoHelp': 'JPG, PNG or WebP · maximum 2 MB', 'settings.name': 'Name', 'settings.yourColor': 'Your colour', 'settings.colorInUse': 'Your partner already uses this colour', 'settings.saveProfile': 'Save profile',
  'settings.appearanceTitle': 'Appearance', 'settings.appearanceDescription': 'Saved only on this device.', 'settings.theme': 'Theme', 'settings.light': 'Light', 'settings.dark': 'Dark', 'settings.system': 'System', 'settings.accent': 'Accent colour', 'settings.language': 'Language', 'settings.languageDescription': 'The language is also saved on this device.', 'settings.spanish': 'Español', 'settings.english': 'English',
  'settings.spaceTitle': 'Shared space', 'settings.spaceDescription': 'The name you will see when you enter.', 'settings.ownerOnly': 'Only the person who created the space can change this name.', 'settings.inviteTitle': 'Invite your partner', 'settings.inviteDescription': 'Share this code once.', 'settings.copyCode': 'Copy code', 'settings.inviteHelp': 'Anyone using the code can view and edit the shared content.',
  'settings.passwordTitle': 'Change password', 'settings.passwordDescription': 'No email is sent and the change is immediate.', 'settings.newPassword': 'New password', 'settings.repeatPassword': 'Repeat password', 'settings.updatePassword': 'Update password', 'settings.session': 'Session', 'settings.role': 'Role', 'settings.owner': 'Creator', 'settings.member': 'Member',
  'settings.profileUpdated': 'Profile updated.', 'settings.spaceUpdated': 'Name updated.', 'settings.photoUpdated': 'Photo updated.', 'settings.photoRemoved': 'Photo removed.', 'settings.passwordUpdated': 'Password updated successfully.', 'settings.passwordMismatch': 'The passwords do not match.', 'settings.invalidPhoto': 'Use a JPG, PNG or WebP image.', 'settings.photoTooLarge': 'The image cannot be larger than 2 MB.',
  'color.coral': 'Coral', 'color.sage': 'Sage', 'color.blue': 'Ocean', 'color.plum': 'Plum', 'color.amber': 'Amber', 'color.rose': 'Rose', 'color.ocean': 'Ocean', 'color.forest': 'Forest',
  'auth.kicker': 'Just for you two', 'auth.storyTitle': 'Everything that is yours,', 'auth.storyHighlight': 'in one place.', 'auth.storyDescription': 'Ideas, details, plans and little things worth keeping.', 'auth.sampleNoteLabel': 'A NOTE FOR BOTH OF YOU', 'auth.sampleNote': 'Book our favourite place for Friday ✦', 'auth.sampleWishLabel': 'NEXT GETAWAY', 'auth.sampleWish': 'A house by the sea', 'auth.footer': 'Our corner, our way.', 'auth.welcome': 'Welcome back', 'auth.recoverAccess': 'Recover access', 'auth.enterTitle': 'Enter your space', 'auth.recoverTitle': 'Reset your password', 'auth.enterDescription': 'A private place for everything you share.', 'auth.recoverDescription': 'We will email you a link to choose a new password.', 'auth.email': 'Email', 'auth.password': 'Password', 'auth.enter': 'Enter Duet', 'auth.sendLink': 'Send link', 'auth.forgotPassword': 'I forgot my password', 'auth.backToLogin': 'Back to sign in', 'auth.recoverySent': 'Check your inbox. The link may take a few minutes.', 'auth.privacy': 'Your data is protected and private.',
  'reset.ready': 'All set', 'reset.updatedTitle': 'Password updated', 'reset.updatedDescription': 'You can keep using Duet with your new password.', 'reset.enter': 'Enter Duet', 'reset.title': 'Choose a new password', 'reset.description': 'Use at least eight characters and do not reuse another password.', 'reset.save': 'Save password',
  'onboarding.eyebrow': 'Let’s begin', 'onboarding.title': 'Create your space', 'onboarding.description': 'You only need to do this once. Everything you save afterwards will appear for both of you.', 'onboarding.createTab': 'Create space', 'onboarding.joinTab': 'I have a code', 'onboarding.spaceName': 'Name of your space', 'onboarding.spaceHelp': 'You can change it later in settings.', 'onboarding.code': 'Invitation code', 'onboarding.codeHelp': 'Ask the person who created the space.', 'onboarding.create': 'Create our space', 'onboarding.join': 'Join the space',
  'setup.eyebrow': 'One last step', 'setup.title': 'Connect Duet to Supabase', 'setup.description': 'The app is ready. It only needs your project’s public credentials to save and protect your content.', 'setup.projectTitle': 'Create a project', 'setup.projectDescription': 'In Supabase, run the migration from the supabase/migrations folder.', 'setup.keysTitle': 'Add the keys', 'setup.keysDescription': 'Copy .env.example to .env.local and fill in both values.', 'setup.startTitle': 'Start the app', 'setup.startDescription': 'Restart npm run dev after saving the environment.', 'setup.open': 'Open Supabase',
  'error.noAccess': 'We could not sign you in', 'error.genericTitle': 'Something went wrong', 'error.unexpected': 'Something unexpected happened. Please try again.', 'error.noCouple': 'There is no active couple.', 'error.supabase': 'Supabase is not configured.',
}

type TranslationKey = keyof typeof es
type Replacements = Record<string, string | number>
type LanguageContextValue = {
  language: Language
  locale: string
  setLanguage: (language: Language) => void
  t: (key: TranslationKey, replacements?: Replacements) => string
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined)

export function LanguageProvider({ children }: PropsWithChildren) {
  const [language, setLanguage] = useState<Language>(() =>
    localStorage.getItem('duet-language') === 'en' ? 'en' : 'es',
  )

  useEffect(() => {
    localStorage.setItem('duet-language', language)
    document.documentElement.lang = language
  }, [language])

  const value = useMemo<LanguageContextValue>(() => ({
    language,
    locale: language === 'es' ? 'es-ES' : 'en-GB',
    setLanguage,
    t: (key, replacements = {}) => {
      const template = (language === 'es' ? es : en)[key]
      return Object.entries(replacements).reduce(
        (result, [name, replacement]) => result.replaceAll(`{${name}}`, String(replacement)),
        template,
      )
    },
  }), [language])

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

// The provider and hook form one cohesive localisation module.
// eslint-disable-next-line react-refresh/only-export-components
export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) throw new Error('useLanguage must be used inside LanguageProvider')
  return context
}
